// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SMTools.Kanban.Data;

#nullable disable

namespace SMTools.Kanban.Data.Migrations
{
    [DbContext(typeof(KanbanDbContext))]
    [Migration("20260721140430_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("kanban")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SMTools.Kanban.Models.KanbanCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("InitialEstimation")
                        .HasColumnType("double precision");

                    b.Property<double?>("Remaining")
                        .HasColumnType("double precision");

                    b.Property<string>("RepoBranch")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RepoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedParticipantId");

                    b.HasIndex("AuthorParticipantId");

                    b.HasIndex("ColumnId");

                    b.HasIndex("RoomId");

                    b.ToTable("KanbanCards", "kanban");
                });

            modelBuilder.Entity("SMTools.Kanban.Models.KanbanCardComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorParticipantId");

                    b.HasIndex("CardId");

                    b.ToTable("KanbanCardComments", "kanban");
                });

            modelBuilder.Entity("SMTools.Kanban.Models.KanbanColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "DisplayOrder");

                    b.ToTable("KanbanColumns", "kanban");
                });

            modelBuilder.Entity("SMTools.Kanban.Models.KanbanRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoomPassword")
                        .HasColumnType("text")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("KanbanRooms", "kanban");
                });

            modelBuilder.Entity("SMTools.Kanban.Models.KanbanRoomParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("HasLeft")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId")
                        .HasFilter("\"ConnectionId\" IS NOT NULL AND \"ConnectionId\" <> ''");

                    b.HasIndex("RoomId")
                        .IsUnique()
                        .HasFilter("\"IsOwner\" = true");

                    b.HasIndex("RoomId", "UserId");

                    b.ToTable("KanbanRoomParticipants", "kanban");
                });

            modelBuilder.Entity("SMTools.Kanban.Models.KanbanCard", b =>
                {
                    b.HasOne("SMTools.Kanban.Models.KanbanRoomParticipant", "Assignee")
                        .WithMany("AssignedCards")
                        .HasForeignKey("AssignedParticipantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SMTools.Kanban.Models.KanbanRoomParticipant", "AuthorParticipant")
                        .WithMany("AuthoredCards")
                        .HasForeignKey("AuthorParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMTools.Kanban.Models.KanbanColumn", "Column")
                        .WithMany("Cards")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMTools.Kanban.Models.KanbanRoom", "Room")
                        .WithMany("Cards")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("AuthorParticipant");

                    b.Navigation("Column");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SMTools.Kanban.Models.KanbanCardComment", b =>
                {
                    b.HasOne("SMTools.Kanban.Models.KanbanRoomParticipant", "AuthorParticipant")
                        .WithMany()
                        .HasForeignKey("AuthorParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMTools.Kanban.Models.KanbanCard", "Card")
                        .WithMany("Comments")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorParticipant");

                    b.Navigation("Card");
                });

            modelBuilder.Entity("SMTools.Kanban.Models.KanbanColumn", b =>
                {
                    b.HasOne("SMTools.Kanban.Models.KanbanRoom", "Room")
                        .WithMany("Columns")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SMTools.Kanban.Models.KanbanRoomParticipant", b =>
                {
                    b.HasOne("SMTools.Kanban.Models.KanbanRoom", "Room")
                        .WithMany("Participants")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SMTools.Kanban.Models.KanbanCard", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("SMTools.Kanban.Models.KanbanColumn", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("SMTools.Kanban.Models.KanbanRoom", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Columns");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("SMTools.Kanban.Models.KanbanRoomParticipant", b =>
                {
                    b.Navigation("AssignedCards");

                    b.Navigation("AuthoredCards");
                });
#pragma warning restore 612, 618
        }
    }
}
