// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SMTools.PlanningPoker.Data;

#nullable disable

namespace SMTools.PlanningPoker.Data.Migrations
{
    [DbContext(typeof(PlanningPokerDbContext))]
    [Migration("20260721140432_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("planningpoker")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SMTools.PlanningPoker.Models.PlanningPokerCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("PlanningPokerCards", "planningpoker");
                });

            modelBuilder.Entity("SMTools.PlanningPoker.Models.PlanningPokerDeck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("PlanningPokerDecks", "planningpoker");
                });

            modelBuilder.Entity("SMTools.PlanningPoker.Models.PlanningPokerRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoomPassword")
                        .HasColumnType("text")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("PlanningPokerRooms", "planningpoker");
                });

            modelBuilder.Entity("SMTools.PlanningPoker.Models.PlanningPokerRoomParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("HasLeft")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId")
                        .HasFilter("\"ConnectionId\" IS NOT NULL AND \"ConnectionId\" <> ''");

                    b.HasIndex("RoomId")
                        .IsUnique()
                        .HasFilter("\"IsOwner\" = true");

                    b.HasIndex("RoomId", "UserId");

                    b.ToTable("PlanningPokerRoomParticipants", "planningpoker");
                });

            modelBuilder.Entity("SMTools.PlanningPoker.Models.PlanningPokerVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("VoteItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("RoomId");

                    b.HasIndex("VoteItemId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("PlanningPokerVotes", "planningpoker");
                });

            modelBuilder.Entity("SMTools.PlanningPoker.Models.PlanningPokerVoteItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevealed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("PlanningPokerVoteItems", "planningpoker");
                });

            modelBuilder.Entity("SMTools.PlanningPoker.Models.PlanningPokerCard", b =>
                {
                    b.HasOne("SMTools.PlanningPoker.Models.PlanningPokerDeck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("SMTools.PlanningPoker.Models.PlanningPokerRoom", b =>
                {
                    b.HasOne("SMTools.PlanningPoker.Models.PlanningPokerDeck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("SMTools.PlanningPoker.Models.PlanningPokerRoomParticipant", b =>
                {
                    b.HasOne("SMTools.PlanningPoker.Models.PlanningPokerRoom", "Room")
                        .WithMany("Participants")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SMTools.PlanningPoker.Models.PlanningPokerVote", b =>
                {
                    b.HasOne("SMTools.PlanningPoker.Models.PlanningPokerRoomParticipant", "Participant")
                        .WithMany("Votes")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMTools.PlanningPoker.Models.PlanningPokerRoom", "Room")
                        .WithMany("Votes")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMTools.PlanningPoker.Models.PlanningPokerVoteItem", "VoteItem")
                        .WithMany("Votes")
                        .HasForeignKey("VoteItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Room");

                    b.Navigation("VoteItem");
                });

            modelBuilder.Entity("SMTools.PlanningPoker.Models.PlanningPokerVoteItem", b =>
                {
                    b.HasOne("SMTools.PlanningPoker.Models.PlanningPokerRoom", "Room")
                        .WithMany("VoteItems")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SMTools.PlanningPoker.Models.PlanningPokerDeck", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("SMTools.PlanningPoker.Models.PlanningPokerRoom", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("VoteItems");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("SMTools.PlanningPoker.Models.PlanningPokerRoomParticipant", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("SMTools.PlanningPoker.Models.PlanningPokerVoteItem", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
