// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SMTools.Retro.Data;

#nullable disable

namespace SMTools.Retro.Data.Migrations
{
    [DbContext(typeof(RetroDbContext))]
    partial class RetroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("retro")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SMTools.Retro.Models.RetroActionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneeParticipantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeParticipantId");

                    b.HasIndex("RoomId");

                    b.ToTable("RetroActionItems", "retro");
                });

            modelBuilder.Entity("SMTools.Retro.Models.RetroCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorParticipantId");

                    b.HasIndex("ColumnId");

                    b.HasIndex("GroupId");

                    b.HasIndex("RoomId");

                    b.ToTable("RetroCards", "retro");
                });

            modelBuilder.Entity("SMTools.Retro.Models.RetroCardGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RetroCardGroups", "retro");
                });

            modelBuilder.Entity("SMTools.Retro.Models.RetroColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("RetroColumns", "retro");
                });

            modelBuilder.Entity("SMTools.Retro.Models.RetroRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<string>("RoomPassword")
                        .HasColumnType("text")
                        .HasColumnName("PasswordHash");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("RetroRooms", "retro");
                });

            modelBuilder.Entity("SMTools.Retro.Models.RetroRoomParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("HasLeft")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId")
                        .HasFilter("\"ConnectionId\" IS NOT NULL AND \"ConnectionId\" <> ''");

                    b.HasIndex("RoomId")
                        .IsUnique()
                        .HasFilter("\"IsOwner\" = true");

                    b.HasIndex("RoomId", "UserId");

                    b.ToTable("RetroRoomParticipants", "retro");
                });

            modelBuilder.Entity("SMTools.Retro.Models.RetroTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("RetroTemplates", "retro");
                });

            modelBuilder.Entity("SMTools.Retro.Models.RetroVote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("RoomId");

                    b.HasIndex("CardId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("RetroVotes", "retro");
                });

            modelBuilder.Entity("SMTools.Retro.Models.RetroActionItem", b =>
                {
                    b.HasOne("SMTools.Retro.Models.RetroRoomParticipant", "Assignee")
                        .WithMany("AssignedActionItems")
                        .HasForeignKey("AssigneeParticipantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SMTools.Retro.Models.RetroRoom", "Room")
                        .WithMany("ActionItems")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SMTools.Retro.Models.RetroCard", b =>
                {
                    b.HasOne("SMTools.Retro.Models.RetroRoomParticipant", "Author")
                        .WithMany("AuthoredCards")
                        .HasForeignKey("AuthorParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMTools.Retro.Models.RetroColumn", "Column")
                        .WithMany("Cards")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SMTools.Retro.Models.RetroCardGroup", "Group")
                        .WithMany("Cards")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SMTools.Retro.Models.RetroRoom", "Room")
                        .WithMany("Cards")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Column");

                    b.Navigation("Group");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SMTools.Retro.Models.RetroCardGroup", b =>
                {
                    b.HasOne("SMTools.Retro.Models.RetroRoom", "Room")
                        .WithMany("Groups")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SMTools.Retro.Models.RetroColumn", b =>
                {
                    b.HasOne("SMTools.Retro.Models.RetroTemplate", "Template")
                        .WithMany("Columns")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("SMTools.Retro.Models.RetroRoom", b =>
                {
                    b.HasOne("SMTools.Retro.Models.RetroTemplate", "Template")
                        .WithMany("Rooms")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("SMTools.Retro.Models.RetroRoomParticipant", b =>
                {
                    b.HasOne("SMTools.Retro.Models.RetroRoom", "Room")
                        .WithMany("Participants")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SMTools.Retro.Models.RetroVote", b =>
                {
                    b.HasOne("SMTools.Retro.Models.RetroCard", "Card")
                        .WithMany("Votes")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMTools.Retro.Models.RetroRoomParticipant", "Participant")
                        .WithMany("Votes")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMTools.Retro.Models.RetroRoom", "Room")
                        .WithMany("Votes")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Participant");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SMTools.Retro.Models.RetroCard", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("SMTools.Retro.Models.RetroCardGroup", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("SMTools.Retro.Models.RetroColumn", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("SMTools.Retro.Models.RetroRoom", b =>
                {
                    b.Navigation("ActionItems");

                    b.Navigation("Cards");

                    b.Navigation("Groups");

                    b.Navigation("Participants");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("SMTools.Retro.Models.RetroRoomParticipant", b =>
                {
                    b.Navigation("AssignedActionItems");

                    b.Navigation("AuthoredCards");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("SMTools.Retro.Models.RetroTemplate", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
